### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by wbt** [monosux/ethereum-block-by-date#38]
Each time I try to make a call as documented, I get this error:
> moment.js:4227 Uncaught (in promise) RangeError: Maximum call stack size exceeded
at Date.valueOf (<anonymous>)
    at Moment.valueOf (moment.js:4227:1)
    at Moment.unix (moment.js:4231:1)
    at module.exports.getNextBlock (ethereum-block-by-date.js:74:1)
    at module.exports.getNextBlock (ethereum-block-by-date.js:74:1)
    at module.exports.getNextBlock (ethereum-block-by-date.js:74:1)
    at module.exports.getNextBlock (ethereum-block-by-date.js:74:1)
    at module.exports.getNextBlock (ethereum-block-by-date.js:74:1)
    at module.exports.getNextBlock (ethereum-block-by-date.js:74:1)
    at module.exports.getNextBlock (ethereum-block-by-date.js:74:1)
valueOf @ moment.js:4227
unix @ moment.js:4231
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
getNextBlock @ ethereum-block-by-date.js:74
await in getNextBlock (async)
(anonymous) @ App.tsx:174
commitHookEffectListMount @ react-dom.development.js:23150
commitPassiveMountOnFiber @ react-dom.development.js:24926
commitPassiveMountEffects_complete @ react-dom.development.js:24891
commitPassiveMountEffects_begin @ react-dom.development.js:24878
commitPassiveMountEffects @ react-dom.development.js:24866
flushPassiveEffectsImpl @ react-dom.development.js:27039
flushPassiveEffects @ react-dom.development.js:26984
(anonymous) @ react-dom.development.js:26769
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
Show 169 more frames
moment.js:4227 Uncaught (in promise) RangeError: Maximum call stack size exceede

**Comment by wbt** [comment]
Dates were invalid due to lack of integer parsing passing a string to the constructor.
